# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_exam_attempt_app', '0002_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='Description',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Location',
            new_name='job_location',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Time',
            new_name='job_title',
        ),
    ]
